services:
  backend:
    build: .
    ports:
      - "20981:5000"
    restart: always
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/ocean-game
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FRONT_URL=${FRONT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - UPDATE_API_KEY=${UPDATE_API_KEY}
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.4.18
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./data/mongo-data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.0.12
    container_name: redis
    ports:
      - "6379:6379"
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"]
    restart: always

volumes:
  mongo-data:
